language: ruby

before_script:
  - chmod +x ./script/cibuild # or do this locally and commit

script: bundle exec jekyll build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: cle.golf
  skip_cleanup: true
  acl: public_read 
  region: "us-east-1"